const { Solar } = require('lunar-javascript');
const { branchIndex } = require('./constants');
function parseTimezoneHours(tz) { const m = /^([+-])(\d{2}):(\d{2})$/.exec(tz); if (!m) throw new Error(`Invalid timezone: ${tz}`); const sign = m[1] === '-' ? -1 : 1; return sign * (Number(m[2]) + Number(m[3]) / 60); }
function parseLocalDateTime(value) { const [d,t='00:00'] = value.split('T'); const [y,mo,day]=d.split('-').map(Number); const [h,mi=0,s=0]=t.split(':').map(Number); return new Date(Date.UTC(y,mo-1,day,h,mi,s)); }
function formatDateTime(dt) { const p=n=>String(n).padStart(2,'0'); return `${dt.getUTCFullYear()}-${p(dt.getUTCMonth()+1)}-${p(dt.getUTCDate())} ${p(dt.getUTCHours())}:${p(dt.getUTCMinutes())}`; }
function equationOfTimeMinutes(date) { const start = Date.UTC(date.getUTCFullYear(), 0, 0); const day = Math.floor((date.getTime() - start) / 86400000); const b = (2 * Math.PI * (day - 81)) / 364; return 9.87 * Math.sin(2 * b) - 7.53 * Math.cos(b) - 1.5 * Math.sin(b); }
function applyTrueSolarTime(datetime, longitude, timezone, enabled=true, equation=false) { const dt=parseLocalDateTime(datetime); if (!enabled) return dt; const longitudeDelta=(longitude - parseTimezoneHours(timezone)*15)*4; const eotDelta = equation ? equationOfTimeMinutes(dt) : 0; return new Date(dt.getTime()+Math.round(longitudeDelta + eotDelta)*60000); }
function hourBranchIndex(date) { const h=date.getUTCHours(); if (h===23) return 0; return Math.floor((h+1)/2)%12; }
function getCalendar(input) { const opts=input.options||{}; const clock=parseLocalDateTime(input.datetime); const trueSolar=applyTrueSolarTime(input.datetime,input.longitude,input.timezone,opts.true_solar_time!==false, opts.equation_of_time===true); const lunar=Solar.fromYmdHms(trueSolar.getUTCFullYear(), trueSolar.getUTCMonth()+1, trueSolar.getUTCDate(), trueSolar.getUTCHours(), trueSolar.getUTCMinutes(), 0).getLunar(); const ygz=lunar.getYearInGanZhi(); const yearStem=ygz[0], yearBranch=ygz[1]; const hBranch=lunar.getTimeZhi(); return { solar: formatDateTime(clock), trueSolar: formatDateTime(trueSolar), lunarText: `${ygz}年${lunar.getMonthInChinese()}月${lunar.getDayInChinese()}${hBranch}时`, fourPillars: `${lunar.getYearInGanZhiExact()} ${lunar.getMonthInGanZhiExact()} ${lunar.getDayInGanZhiExact()} ${lunar.getTimeInGanZhi()}`, lunarMonth: Math.abs(lunar.getMonth()), lunarDay: lunar.getDay(), hourBranch: branchIndex(hBranch), yearStem, yearBranch, yearBranchIndex: branchIndex(yearBranch) };
}
module.exports={ parseTimezoneHours, parseLocalDateTime, formatDateTime, equationOfTimeMinutes, applyTrueSolarTime, hourBranchIndex, getCalendar };
