const { getCalendar } = require('./calendar');
const { mingShen, buildPalaces, wuxingJu, mingZhu, shenZhu } = require('./palaces');
const { isForward } = require('./constants');
const { majorStars } = require('./stars_major');
const { auxStars } = require('./stars_aux');
const { bornSihua, applyBornTransforms, applySelfTransforms } = require('./sihua');
const { shensha } = require('./shensha');
const { daxianByPalaceIndex, xiaoxian, liunian } = require('./fate_periods');
const { brightness } = require('./brightness');
function buildChart(input){ if(input.calendar!=='solar') throw new Error('Phase 1 only supports solar calendar'); const cal=getCalendar(input); const {ming,shen}=mingShen(cal.lunarMonth, cal.hourBranch); const palaces=buildPalaces(ming,shen,cal.yearStem); const mingPalace=palaces[0]; const ju=wuxingJu(mingPalace.stem, mingPalace.branch); const forward=isForward(cal.yearStem,input.gender); const majors=majorStars(ju.number, cal.lunarDay); const aux=auxStars(cal.yearStem, cal.yearBranchIndex, cal.lunarMonth, cal.hourBranch); const starMap={}; const add=(name,branchIndex,type)=>{ starMap[name]={name,branchIndex,type,bright:brightness(name,branchIndex),transforms:[]};}; Object.entries(majors).forEach(([n,b])=>add(n,b,'majors')); Object.entries(aux).forEach(([n,b])=>add(n,b,'aux')); applyBornTransforms(starMap, cal.yearStem); applySelfTransforms(palaces, starMap); const ss=shensha(ju.name, forward, aux.禄存, cal.yearBranchIndex); const dx=daxianByPalaceIndex(ju.number, forward); const ageRange=input.options?.age_range||[1,60]; const xx=xiaoxian(cal.yearBranchIndex,input.gender,ageRange); const ln=liunian(cal.yearBranchIndex,ageRange); const enriched=palaces.map((p,i)=>({ name:p.name, branch:p.branch, stem:p.stem, ganzhi:p.ganzhi, tags:p.tags, majors:Object.values(starMap).filter(s=>s.type==='majors'&&s.branchIndex===p.branchIndex).map(({name,bright,transforms})=>({name,bright,transforms})), aux:Object.values(starMap).filter(s=>s.type==='aux'&&s.branchIndex===p.branchIndex).map(({name,bright,transforms})=>({name,bright,transforms})), minors:[], shensha:{suiqian:ss.suiqian[p.branchIndex], jiangqian:ss.jiangqian[p.branchIndex], changsheng:ss.changsheng[p.branchIndex], boshi:ss.boshi[p.branchIndex]}, daxian:dx[i], xiaoxian:xx[p.branchIndex], liunian:ln[p.branchIndex] })); return { meta:{gender:input.gender==='female'?'女':'男', solar:cal.solar, true_solar:cal.trueSolar, lunar:cal.lunarText, four_pillars:cal.fourPillars, wuxing_ju:ju.name, ming_gong:mingPalace.branch, shen_gong:palaces.find(p=>p.branchIndex===shen).branch, ming_zhu:mingZhu(ming), shen_zhu:shenZhu(cal.yearBranchIndex)}, born_sihua:bornSihua(cal.yearStem), palaces:enriched }; }
module.exports={ buildChart };
